package:
  name: sygma
  version: 1.1.0

source:
  fn: SyGMa-1.1.0.tar.gz
  md5: 0a398b1d2633e5153c8b588fd823232c
  url: https://pypi.python.org/packages/01/0d/7960ca6076d00ff33bf2aa0ac925074a07820900b8b8ae1edae83d12e488/SyGMa-1.1.0.tar.gz

requirements:
  build:
    - python
    - setuptools
    - rdkit
    - nose
    - future

  run:
    - python
    - setuptools
    - rdkit
    - future

test:
  imports:
    - sygma
    - rdkit

about:
  home: https://github.com/3D-e-Chem/sygma
  license: GPL
  license_file:
