package:
  name: sygma
  version: 1.0.1

source:
  fn: SyGMa-1.0.1.tar.gz
  md5: a797d73abd2680e1b22222006693e540
  url: https://pypi.python.org/packages/62/9e/65b7fbb38f83e187d5af5db02ec7ae710b909644f6d7731ca5dd8ce13e2f/SyGMa-1.0.1.tar.gz

requirements:
  build:
    - python
    - setuptools
    - rdkit
    - nose

  run:
    - python
    - setuptools
    - rdkit

test:
  imports:
    - sygma
    - rdkit

about:
  home: https://github.com/3D-e-Chem/sygma
  license: GPL
  license_file:
