channels:
  targets:
  - [3D-e-Chem, main]
  sources:
  - rdkit
travis:
  secure:
    BINSTAR_TOKEN: sNMMe9LhIzAHns669HLlqXuh8gCRzMIBGkGcz49hWMhATPSB6sItuePTLg2yWxIQjmdSUHJ41ZTU1Xpj3RoVlKgOZ2KOJ9f8VhSZCqOiC51GQmLNjzd4hHleLg7RXKbykuNLRI4O71Wp2Jj24kptSrifdu/d/8d95Q1boFw/fNeIPVV76HbB8mKFf16YjKkx4Ts6NGkWW+2QiSs1nYHCyWJMcSMxDrV+TrtKbHqSKvEm8SRmVt7tH2YL3x8ACEQOU8+RMiOxq9EIy436Z0hoZnd94vk8ste2yL5R+fgzrIoGvwzLRNhou15zff5MuO5E6EbjEoaplMCnt+PMk17FHSw61uFG7CTZijqCfs/J4XNpilDYQWL4vJ/eWR+sK14meD4NFxgXuQPkXu7HPAvv1ZILast/u/VHE8x69sDlcWyisAAov1QkEfw2kHHDBrU2yiUzPFa89++AMO9Rz8kFKcNt98KeOqt9V+G8wdsIW2fxr/8vYzsQPXw0LCn1tf+4E05GmEGbV/uDCQrTs7+QrfQLAJJ1AGrpA0YQ/eDMLRscF/p8O26AQKObK0hW83Wdfm7Vq34c6+aK2QhmW+sgjXDkEgBfK3Gruxk4wmaG9V9NTw1ibEhRGGCkjc9Mf8oaQnq4bIf9A1PS6tv0rOoHtfvbrmfTi0BZ72O1hTKQeHI=
appveyor:
  secure:
    BINSTAR_TOKEN: fzG+V9uXoZu0vcXv34MssmrVEg8Bz/BeE9Vud3/J5f48+l1TiHgnanuhHc9hu7PQ
